### ISSUE TITLE
Problems when running the demo

### ISSUE THREAD

**Issue by Lin239522** [hustvl/VMA#15]
@zyc10ud Thank you for your excellent work！
I want to run demo by the following command
```
/home/wll/anaconda3/envs/vma/bin/python demo/custom_infer.py \
  /home/wll/Project/VMA/demo/image_data \
  projects/configs/vma_icurb.py \
  ckpts/sd_line.pth \
  --trajectory_sample_num 15 \
  --element_type line \
  --out_dir output \
  --visualize False
```
The following error message appears. I did not crop or modify the input image. Is there something wrong with my execution steps or commands?
```
Traceback (most recent call last):
  File "demo/custom_infer.py", line 64, in <module>
    main()
  File "demo/custom_infer.py", line 60, in main
    infer_combine_function(args, data_list)
  File "/home/wll/Project/VMA/demo/inference_and_combine_function.py", line 223, in driving_line_infer_and_save
    results_list, left_top = inference_detector_forcurb_bigimg(model, get_sub_data_driving, upload_img_path, trajectory_path, args.trajectory_sample_num, get_traj_pad=True, pad=False, attr=True)
  File "/home/wll/Project/VMA/demo/inference_and_combine_function.py", line 175, in inference_detector_forcurb_bigimg
    result = model(return_loss=False, rescale=True, **data)
  File "/home/wll/anaconda3/envs/vma/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wll/Project/VMA/projects/mmdet3d_plugin/vma/detectors/vma.py", line 114, in forward
    return self.forward_test(**kwargs)
  File "/home/wll/Project/VMA/projects/mmdet3d_plugin/vma/detectors/vma.py", line 158, in forward_test
    bbox_results = self.simple_test(
  File "/home/wll/Project/VMA/projects/mmdet3d_plugin/vma/detectors/vma.py", line 219, in simple_test
    img_feats = self.extract_feat(img=img, img_metas=img_metas)
  File "/home/wll/anaconda3/envs/vma/lib/python3.8/site-packages/mmcv/runner/fp16_utils.py", line 98, in new_func
    return old_func(*args, **kwargs)
  File "/home/wll/Project/VMA/projects/mmdet3d_plugin/vma/detectors/vma.py", line 69, in extract_feat
    img_feats = self.extract_img_feat(img)
  File "/home/wll/Project/VMA/projects/mmdet3d_plugin/vma/detectors/vma.py", line 53, in extract_img_feat
    img_feats = self.img_backbone(img)
  File "/home/wll/anaconda3/envs/vma/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wll/Project/VMA/projects/mmdet3d_plugin/vma/backbones/icurb_backbone.py", line 66, in forward
    x = F.relu(self.bn1(self.conv1(x)))
  File "/home/wll/anaconda3/envs/vma/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/wll/anaconda3/envs/vma/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 443, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/wll/anaconda3/envs/vma/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 439, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [64, 4, 7, 7], expected input[1, 3, 1000, 1000] to have 4 channels, but got 3 channels instead
```

**Comment by iwander-all** [comment]
the same, none of the commands in demo readme is played successfully in my try

**Comment by iwander-all** [comment]
@Lin239522 终于玩出来了，指令是这样的：
`python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_res152_e80_line.py  ./ckpts/sd_line.pth --trajectory_sample_num 2 --element_type line --out_dir ./demo/out/ --visualize True

python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_res152_e80_box.py  ./ckpts/sd_box.pth --trajectory_sample_num 2 --element_type box --out_dir ./demo/out/ --visualize True

python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_icurb_backbone_e80_freespace.py  ./ckpts/sd_freespace.pth --trajectory_sample_num 2 --element_type freespace --out_dir ./demo/out/ --visualize True`

咋说呢，预测的不是很准啊....

![sample_2_driving_line](https://github.com/user-attachments/assets/147b5644-2350-43be-9488-e5fe1c476d55)
![sample_2_driving_freespace](https://github.com/user-attachments/assets/bef64664-6984-48eb-83b4-fdab368ac42d)
![sample_2_driving_box](https://github.com/user-attachments/assets/50fa0a91-4d86-442f-864d-17c40d7e300c)
![sample_1_driving_line](https://github.com/user-attachments/assets/e1fa1114-456b-4788-8173-2a0dcebf2e68)
![sample_1_driving_freespace](https://github.com/user-attachments/assets/5591b8ca-d790-47f8-a0ca-15ccf2205ade)
![sample_1_driving_box](https://github.com/user-attachments/assets/650cc497-7da4-402c-9852-fa9768ea8f2c)

**Comment by Lin239522** [comment]
> @Lin239522 终于玩出来了，指令是这样的： `python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_res152_e80_line.py ./ckpts/sd_line.pth --trajectory_sample_num 2 --element_type line --out_dir ./demo/out/ --visualize True
> 
> python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_res152_e80_box.py ./ckpts/sd_box.pth --trajectory_sample_num 2 --element_type box --out_dir ./demo/out/ --visualize True
> 
> python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_icurb_backbone_e80_freespace.py ./ckpts/sd_freespace.pth --trajectory_sample_num 2 --element_type freespace --out_dir ./demo/out/ --visualize True`
> 
> 咋说呢，预测的不是很准啊....
> 
> ![sample_2_driving_line](https://private-user-images.githubusercontent.com/58039345/352011936-147b5644-2350-43be-9488-e5fe1c476d55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5MzYtMTQ3YjU2NDQtMjM1MC00M2JlLTk0ODgtZTVmZTFjNDc2ZDU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwODI4ZTJiMDg3OWZmNWNhODE2Mzg0NDNmZDczNzRmOTBjYzUyNzRlNTQyMGI1MTQ5ZWVhMzVmNjI5NDM1ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o3B0w735rr16cjRvkhoUpKiTptpvwvJkHKBUlWJd-lw) ![sample_2_driving_freespace](https://private-user-images.githubusercontent.com/58039345/352011952-bef64664-6984-48eb-83b4-fdab368ac42d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5NTItYmVmNjQ2NjQtNjk4NC00OGViLTgzYjQtZmRhYjM2OGFjNDJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NmQwNzE3N2Q5YzA1MTk3N2IxMzFhNGUzMGI3NDAwNjc0ZmVhNDQ5N2IzOTE4MGU1YTkwMjlhY2IwZjFiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OvoKaw_2o0BQQ8lMdhQE-zUYEwHjjuwIBKeTJpuBuQU) ![sample_2_driving_box](https://private-user-images.githubusercontent.com/58039345/352011962-50fa0a91-4d86-442f-864d-17c40d7e300c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5NjItNTBmYTBhOTEtNGQ4Ni00NDJmLTg2NGQtMTdjNDBkN2UzMDBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDUzYzRhN2E5MjM3OTEyODA0ZmNmODNmYzlkODU0ZDc2ZmUwYjhkZDdkODhiOGY5ZjIzNjc4MzM1YzA4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAcAhj1YgPjXJKm6itTkmndwyRtq6WmVqP4fGEKawMg) ![sample_1_driving_line](https://private-user-images.githubusercontent.com/58039345/352011971-e1fa1114-456b-4788-8173-2a0dcebf2e68.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5NzEtZTFmYTExMTQtNDU2Yi00Nzg4LTgxNzMtMmEwZGNlYmYyZTY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYjA2ZTM3MmJiZWIyNjE4NjIyMzlkZGQ3NDUzMDg3NzQ3ZjQ4NzgxMTJlOTg0OWRhNzE5NDFlYjY0MzM4MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1GBhnN93mTmcrFolNaZDYrav9s-JehqtitUbniRoLM) ![sample_1_driving_freespace](https://private-user-images.githubusercontent.com/58039345/352011983-5591b8ca-d790-47f8-a0ca-15ccf2205ade.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5ODMtNTU5MWI4Y2EtZDc5MC00N2Y4LWEwY2EtMTVjY2YyMjA1YWRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NWEyNjYwNGQyMDEyMTkxMWIxZWU3ZDk2YThlZmY2NTUzODQ4NDM4ZWEyYWU4MjRmZTBkZmUyMTk3YmQ3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hWVJu4MajLGwgfIweRYaw_VDKUl7_IZnhgZ9mAN0CY) ![sample_1_driving_box](https://private-user-images.githubusercontent.com/58039345/352011991-650cc497-7da4-402c-9852-fa9768ea8f2c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5OTEtNjUwY2M0OTctN2RhNC00MDJjLTk4NTItZmE5NzY4ZWE4ZjJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzVhYTUxMDNiNjkyMjZjMDQyMTkwNDFkYWJjODMxOGU2NDU1ZWYzZmY1ODFkZTUxZjFmOWVhNjliYTI3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qxMLFFiqKLBEyR2bI1KiTUMHZPPinjHjd4v6WeLwnQ)

输入应该是图像+json? 请问你知道 demo里面的 (demo/trajectory_data/sample_1.json) 是怎么得到的吗

**Comment by iwander-all** [comment]
我也不造...只是跑通了这个demo，太磨人了

**Comment by lonelyriki** [comment]
> > @Lin239522 终于玩出来了，指令是这样的： `python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_res152_e80_line.py ./ckpts/sd_line.pth --trajectory_sample_num 2 --element_type line --out_dir ./demo/out/ --visualize True
> > python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_res152_e80_box.py ./ckpts/sd_box.pth --trajectory_sample_num 2 --element_type box --out_dir ./demo/out/ --visualize True
> > python ./demo/custom_infer.py ./demo/image_data/ ./projects/configs/vma_icurb_backbone_e80_freespace.py ./ckpts/sd_freespace.pth --trajectory_sample_num 2 --element_type freespace --out_dir ./demo/out/ --visualize True`
> > 咋说呢，预测的不是很准啊....
> > ![sample_2_driving_line](https://private-user-images.githubusercontent.com/58039345/352011936-147b5644-2350-43be-9488-e5fe1c476d55.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5MzYtMTQ3YjU2NDQtMjM1MC00M2JlLTk0ODgtZTVmZTFjNDc2ZDU1LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIwODI4ZTJiMDg3OWZmNWNhODE2Mzg0NDNmZDczNzRmOTBjYzUyNzRlNTQyMGI1MTQ5ZWVhMzVmNjI5NDM1ODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o3B0w735rr16cjRvkhoUpKiTptpvwvJkHKBUlWJd-lw) ![sample_2_driving_freespace](https://private-user-images.githubusercontent.com/58039345/352011952-bef64664-6984-48eb-83b4-fdab368ac42d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5NTItYmVmNjQ2NjQtNjk4NC00OGViLTgzYjQtZmRhYjM2OGFjNDJkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NmQwNzE3N2Q5YzA1MTk3N2IxMzFhNGUzMGI3NDAwNjc0ZmVhNDQ5N2IzOTE4MGU1YTkwMjlhY2IwZjFiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OvoKaw_2o0BQQ8lMdhQE-zUYEwHjjuwIBKeTJpuBuQU) ![sample_2_driving_box](https://private-user-images.githubusercontent.com/58039345/352011962-50fa0a91-4d86-442f-864d-17c40d7e300c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5NjItNTBmYTBhOTEtNGQ4Ni00NDJmLTg2NGQtMTdjNDBkN2UzMDBjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZDUzYzRhN2E5MjM3OTEyODA0ZmNmODNmYzlkODU0ZDc2ZmUwYjhkZDdkODhiOGY5ZjIzNjc4MzM1YzA4YmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAcAhj1YgPjXJKm6itTkmndwyRtq6WmVqP4fGEKawMg) ![sample_1_driving_line](https://private-user-images.githubusercontent.com/58039345/352011971-e1fa1114-456b-4788-8173-2a0dcebf2e68.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5NzEtZTFmYTExMTQtNDU2Yi00Nzg4LTgxNzMtMmEwZGNlYmYyZTY4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjYjA2ZTM3MmJiZWIyNjE4NjIyMzlkZGQ3NDUzMDg3NzQ3ZjQ4NzgxMTJlOTg0OWRhNzE5NDFlYjY0MzM4MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p1GBhnN93mTmcrFolNaZDYrav9s-JehqtitUbniRoLM) ![sample_1_driving_freespace](https://private-user-images.githubusercontent.com/58039345/352011983-5591b8ca-d790-47f8-a0ca-15ccf2205ade.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5ODMtNTU5MWI4Y2EtZDc5MC00N2Y4LWEwY2EtMTVjY2YyMjA1YWRlLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2NWEyNjYwNGQyMDEyMTkxMWIxZWU3ZDk2YThlZmY2NTUzODQ4NDM4ZWEyYWU4MjRmZTBkZmUyMTk3YmQ3NGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._hWVJu4MajLGwgfIweRYaw_VDKUl7_IZnhgZ9mAN0CY) ![sample_1_driving_box](https://private-user-images.githubusercontent.com/58039345/352011991-650cc497-7da4-402c-9852-fa9768ea8f2c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5NTcxMDAsIm5iZiI6MTcyMTk1NjgwMCwicGF0aCI6Ii81ODAzOTM0NS8zNTIwMTE5OTEtNjUwY2M0OTctN2RhNC00MDJjLTk4NTItZmE5NzY4ZWE4ZjJjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDAxMjAwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzVhYTUxMDNiNjkyMjZjMDQyMTkwNDFkYWJjODMxOGU2NDU1ZWYzZmY1ODFkZTUxZjFmOWVhNjliYTI3MjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._qxMLFFiqKLBEyR2bI1KiTUMHZPPinjHjd4v6WeLwnQ)
> 
> 输入应该是图像+json? 请问你知道 demo里面的 (demo/trajectory_data/sample_1.json) 是怎么得到的吗

这个是轨迹数据啊,是做数据的人自己处理的.....
